dependencies {
    implementation libs.springBootStarterWeb
    implementation libs.springBootDataMongo
    implementation libs.springBootStarterAmqp
    implementation libs.springCloudEurekaClient

    // --- FEIGN CLIENT ---
    implementation libs.springCloudStarterOpenFeign

    // --- GÜVENLİK ---
    implementation libs.springSecurityOAuth2ResourceServer
    implementation libs.springSecurityConfig

    // Boilerplate
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    implementation libs.mapStruct
    annotationProcessor libs.mapStructProcessor

    // ✅ ZIPKIN & TRACING BAĞIMLILIKLARI (EKLENDİ)
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
}