dependencies {
    // --- 1. GATEWAY & REACTIVE WEB ---
    implementation libs.springCloudGateway
    implementation libs.springBootStarterWebFlux
    implementation libs.springCloudCircuitBreakerReactor

    // --- 2. DISCOVERY & CONFIG ---
    implementation libs.springCloudEurekaClient
    implementation libs.springCloudConfigClient

    // --- 3. SECURITY (OAUTH2 & BASIC) ---
    implementation libs.springSecurityConfig               // Temel Security
    implementation libs.springSecurityOAuth2ResourceServer // Resource Server Desteği
    implementation libs.springSecurityOAuth2Client         // Login Client Desteği (BFF)

    // --- 4. SESSION MANAGEMENT (REDIS) ---
    implementation libs.springSessionDataRedis // Session'ı Redis'te tutar
    implementation libs.springBootDataRedis    // Redis bağlantısı

    // --- 5. OBSERVABILITY (ZIPKIN & TRACING) --- ✅ EKLENEN KISIM
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'

    // --- 6. UTILS ---
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}