server:
  port: 8083

spring:
  application:
    name: recommendation-service

  # --- MONGODB ---
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce-recommendation-db
      username: admin
      password: admin
      authentication-database: admin

  # --- RABBITMQ ---
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

  # --- GÜVENLİK ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8180/realms/ecommerce-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ✅ ZIPKIN AYARLARI EKLENDİ
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

# ✅ LOGLAMA AYARLARI EKLENDİ
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"