dependencies {
    implementation libs.springBootStarterWeb
    implementation libs.springBootDataJpa
    implementation libs.postgreSQL
    implementation libs.springCloudEurekaClient
    implementation libs.springSecurityOAuth2ResourceServer

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    // Feign Client
    implementation libs.springCloudStarterOpenFeign

    // ✅ ZIPKIN & TRACING BAĞIMLILIKLARI (EKLENDİ)
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
}