dependencies {
    // 1. WEB & API
    implementation libs.springBootStarterWeb
    implementation libs.swaggerui

    // 2. VERİTABANI KATMANI
    implementation libs.springBootDataJpa
    implementation libs.postgreSQL
    implementation libs.hypersistenceUtils

    // 3. MİKROSERVİS İLETİŞİMİ
    implementation libs.springCloudEurekaClient
    implementation libs.springCloudStarterOpenFeign
    implementation libs.springBootStarterAmqp

    // 4. GÜVENLİK
    implementation libs.springSecurityConfig
    implementation libs.springSecurityOAuth2ResourceServer

    // 5. BULUT & DOSYA
    implementation libs.awsSdkS3

    // 6. ARAÇLAR & UTILS
    implementation libs.mapStruct
    implementation libs.jacksonDatatypeJsr310
    compileOnly libs.lombok

    // 7. ANNOTATION PROCESSORS
    annotationProcessor libs.lombok
    annotationProcessor libs.mapStructProcessor

    // ✅ ZIPKIN & TRACING BAĞIMLILIKLARI (EKLENDİ)
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
}