server:
  port: 8082

spring:
  application:
    name: user-service

  # --- RABBITMQ AYARLARI ---
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

  # --- MONGODB AYARLARI ---
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce-user-db
      username: admin
      password: admin
      authentication-database: admin

    # --- REDIS AYARLARI ---
    redis:
      host: localhost
      port: 6379

  # --- CACHE AYARLARI ---
  cache:
    type: redis

  # --- GÜVENLİK ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8180/realms/ecommerce-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# KEYCLOAK ADMIN CLIENT AYARLARI
keycloak:
  admin:
    client-id: user-service-client
    client-secret: uRN5hXdF8ET3uO1jAom529UzANZLPMEt

# ✅ ZIPKIN AYARLARI EKLENDİ
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

# ✅ LOGLAMA AYARLARI EKLENDİ
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"