dependencies {
    // 1. WEB & CORE
    implementation libs.springBootStarterWeb
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator' // Sağlık kontrolü ve Metrikler

    // 2. DATA
    implementation libs.springBootDataJpa
    implementation libs.postgreSQL
    implementation libs.springBootDataRedis

    // 3. MICROSERVICES
    implementation libs.springCloudEurekaClient
    implementation libs.springCloudStarterOpenFeign
    implementation libs.springBootStarterAmqp

    // 4. SECURITY
    implementation libs.springSecurityOAuth2ResourceServer

    // 5. UTILS
    implementation libs.mapStruct
    implementation libs.swaggerui
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    annotationProcessor libs.mapStructProcessor

    // ✅ ZIPKIN & TRACING BAĞIMLILIKLARI
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
    // Prometheus (Opsiyonel ama grafana için iyi olur)
    implementation 'io.micrometer:micrometer-registry-prometheus'
}