server:
  port: 8093

spring:
  application:
    name: search-service

  # --- ELASTICSEARCH AYARLARI ---
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 3s

  # --- RABBITMQ AYARLARI ---
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# --- SERVICE DISCOVERY (EUREKA) ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ✅ ZIPKIN AYARLARI EKLENDİ
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

# ✅ LOGLAMA AYARLARI GÜNCELLENDİ
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE
    org.springframework.data.elasticsearch.core: DEBUG