server:
  port: 8086

spring:
  application:
    name: feedback-service

  # --- MULTIPART AYARLARI ---
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 25MB
      file-size-threshold: 2KB

  # --- JACKSON AYARLARI ---
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

  # --- MONGODB AYARLARI ---
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce-feedback-db
      username: admin
      password: admin
      authentication-database: admin

  # --- RABBITMQ AYARLARI ---
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

  # --- GÜVENLİK ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ecommerce-realm
          jwk-set-uri: http://localhost:8180/realms/ecommerce-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ✅ ZIPKIN AYARLARI EKLENDİ
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

# ✅ LOGLAMA AYARLARI EKLENDİ
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"